[workspace]
members = [".", "hash-literal-core"]

[package]
name = "sha3-literal"
version = "0.1.3"
edition = "2024"
license = "CC0-1.0"
description = "Literals for Sha3 hashes"

[dependencies]
hash-literal-core = { path = "./hash-literal-core" }
sha3 = "^0.10.8"

[lib]
proc-macro = true
